/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.juego;

import java.awt.Color;

/**
 *
 * @author ASUS
 */
public class Vista extends javax.swing.JFrame {

    /**
     * Creates new form Vista
     */
    public Vista() {
        initComponents();
        
        panel1.setBackground(Color.red);
        panel2.setBackground(Color.blue);
        llenar();
        diagonal1.setVisible(false);
        diagonal2.setVisible(false);
        izquierdavertical.setVisible(false);
        centrovertical.setVisible(false);
        derechavertical.setVisible(false);
        fila1.setVisible(false);
        fila2.setVisible(false);
        fila3.setVisible(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
            
            
            
            
            
            
    int m[][] =new  int [3][3];
    public void llenar(){
        for (int i = 0; i < 3; i++) {
            for (int j = 0; j < 3; j++) {
                m[i][j]=(j+10)*(i+10);
            }
        }
    }
   
    Principal l=new Principal(0,0,0);
    
    public void turnar(){
        if(l.getTurno()==1){
            panel1.setBackground(Color.red);
            panel2.setBackground(Color.blue);
            
        }
        if(l.getTurno()==0){
            panel1.setBackground(Color.blue);
            panel2.setBackground(Color.red);
            
        }
    }
    public void reiniciar(){
        llenar();
        btn00.setText("");
        btn00.setEnabled(true);
        btn01.setText("");
        btn01.setEnabled(true);
        btn02.setText("");
        btn02.setEnabled(true);
        btn10.setText("");
        btn10.setEnabled(true);
        btn11.setText("");
        btn11.setEnabled(true);
        btn12.setText("");
        btn12.setEnabled(true);
        btn20.setText("");
        btn20.setEnabled(true);
        btn21.setText("");
        btn21.setEnabled(true);
        btn22.setText("");
        btn22.setEnabled(true);
        diagonal1.setVisible(false);
        diagonal2.setVisible(false);
        izquierdavertical.setVisible(false);
        centrovertical.setVisible(false);
        derechavertical.setVisible(false);
        fila1.setVisible(false);
        fila2.setVisible(false);
        fila3.setVisible(false);
        
        
    }
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        diagonal2 = new javax.swing.JLabel();
        diagonal1 = new javax.swing.JLabel();
        izquierdavertical = new javax.swing.JPanel();
        fila2 = new javax.swing.JPanel();
        fila3 = new javax.swing.JPanel();
        centrovertical = new javax.swing.JPanel();
        derechavertical = new javax.swing.JPanel();
        fila1 = new javax.swing.JPanel();
        btn20 = new javax.swing.JButton();
        btn01 = new javax.swing.JButton();
        btn12 = new javax.swing.JButton();
        btn10 = new javax.swing.JButton();
        btn00 = new javax.swing.JButton();
        btn11 = new javax.swing.JButton();
        btn02 = new javax.swing.JButton();
        btn21 = new javax.swing.JButton();
        btn22 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        Panel1 = new javax.swing.JPanel();
        panel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jo = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        panel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jx = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Juego tres en raya");
        setBackground(new java.awt.Color(0, 0, 204));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("Juego"); // NOI18N

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        diagonal2.setText("jLabel6");
        jPanel3.add(diagonal2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, -1));

        diagonal1.setText("jLabel5");
        jPanel3.add(diagonal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, -1));

        izquierdavertical.setBackground(new java.awt.Color(51, 51, 255));

        javax.swing.GroupLayout izquierdaverticalLayout = new javax.swing.GroupLayout(izquierdavertical);
        izquierdavertical.setLayout(izquierdaverticalLayout);
        izquierdaverticalLayout.setHorizontalGroup(
            izquierdaverticalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        izquierdaverticalLayout.setVerticalGroup(
            izquierdaverticalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );

        jPanel3.add(izquierdavertical, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 10, 230));

        fila2.setBackground(new java.awt.Color(51, 51, 255));

        javax.swing.GroupLayout fila2Layout = new javax.swing.GroupLayout(fila2);
        fila2.setLayout(fila2Layout);
        fila2Layout.setHorizontalGroup(
            fila2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );
        fila2Layout.setVerticalGroup(
            fila2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );

        jPanel3.add(fila2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        fila3.setBackground(new java.awt.Color(51, 51, 255));

        javax.swing.GroupLayout fila3Layout = new javax.swing.GroupLayout(fila3);
        fila3.setLayout(fila3Layout);
        fila3Layout.setHorizontalGroup(
            fila3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );
        fila3Layout.setVerticalGroup(
            fila3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );

        jPanel3.add(fila3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        centrovertical.setBackground(new java.awt.Color(51, 51, 255));

        javax.swing.GroupLayout centroverticalLayout = new javax.swing.GroupLayout(centrovertical);
        centrovertical.setLayout(centroverticalLayout);
        centroverticalLayout.setHorizontalGroup(
            centroverticalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        centroverticalLayout.setVerticalGroup(
            centroverticalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );

        jPanel3.add(centrovertical, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));

        derechavertical.setBackground(new java.awt.Color(51, 51, 255));

        javax.swing.GroupLayout derechaverticalLayout = new javax.swing.GroupLayout(derechavertical);
        derechavertical.setLayout(derechaverticalLayout);
        derechaverticalLayout.setHorizontalGroup(
            derechaverticalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        derechaverticalLayout.setVerticalGroup(
            derechaverticalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );

        jPanel3.add(derechavertical, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, -1, -1));

        fila1.setBackground(new java.awt.Color(51, 51, 255));

        javax.swing.GroupLayout fila1Layout = new javax.swing.GroupLayout(fila1);
        fila1.setLayout(fila1Layout);
        fila1Layout.setHorizontalGroup(
            fila1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );
        fila1Layout.setVerticalGroup(
            fila1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel3.add(fila1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 54, 210, 10));

        btn20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn20ActionPerformed(evt);
            }
        });
        jPanel3.add(btn20, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 177, 63, 70));

        btn01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn01ActionPerformed(evt);
            }
        });
        jPanel3.add(btn01, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 20, 63, 70));

        btn12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn12ActionPerformed(evt);
            }
        });
        jPanel3.add(btn12, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 96, 63, 70));

        btn10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn10ActionPerformed(evt);
            }
        });
        jPanel3.add(btn10, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 96, 63, 70));

        btn00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn00ActionPerformed(evt);
            }
        });
        jPanel3.add(btn00, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 63, 70));

        btn11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn11ActionPerformed(evt);
            }
        });
        jPanel3.add(btn11, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 96, 63, 70));

        btn02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn02ActionPerformed(evt);
            }
        });
        jPanel3.add(btn02, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 20, 63, 70));

        btn21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn21ActionPerformed(evt);
            }
        });
        jPanel3.add(btn21, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 177, 63, 70));

        btn22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn22ActionPerformed(evt);
            }
        });
        jPanel3.add(btn22, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 177, 63, 70));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 153, 153));
        jButton1.setText("Reiniciar juego");
        jButton1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 30, 108, -1));

        Panel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        panel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/img/dos (2).png"))); // NOI18N

        jo.setText("0");

        jTextField2.setText("Jugador 2");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jo, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        panel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/img/uno (2).png"))); // NOI18N

        jx.setText("0");

        jTextField1.setText("Jugador1");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jx, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel1Layout.createSequentialGroup()
                        .addGap(0, 7, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jx, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout Panel1Layout = new javax.swing.GroupLayout(Panel1);
        Panel1.setLayout(Panel1Layout);
        Panel1Layout.setHorizontalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(panel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        Panel1Layout.setVerticalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(28, 28, 28))
        );

        jPanel3.add(Panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 53, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn01ActionPerformed
        // TODO add your handling code here:
        turnar(); 
        l.raya(m, fila1, 1, 0, 1);
         if(l.ejecutar(btn01, 0, 1, m, jx, jo)==1){
             reiniciar();
         }
    }//GEN-LAST:event_btn01ActionPerformed

    private void btn10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn10ActionPerformed

    private void btn11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn11ActionPerformed
        // TODO add your handling code here:
        turnar();
     l.raya(m, diagonal1, 7, 0, 0);
        l.raya(m, diagonal1, 7, 1, 1);
       if(l.ejecutar(btn11, 1, 1, m, jx, jo)==1){
           reiniciar();
       }
    }//GEN-LAST:event_btn11ActionPerformed

    private void btn21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn21ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void btn00ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn00ActionPerformed
        // TODO add your handling code here:
        turnar();
        l.raya(m, diagonal1, 7, 0, 0);
        l.raya(m, fila1, 1, 0, 0);
        if(l.ejecutar(btn00, 0, 0, m, jx, jo)==1){
            reiniciar();
        }
    }//GEN-LAST:event_btn00ActionPerformed

    private void btn22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn22ActionPerformed
        // TODO add your handling code here:
        turnar();
        l.raya(m, diagonal1, 7, 2, 2);
      
       if(l.ejecutar(btn22, 2, 2, m, jx, jo)==1){
           reiniciar();
       }
    }//GEN-LAST:event_btn22ActionPerformed

    private void btn02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn02ActionPerformed
        // TODO add your handling code here:
         turnar(); 
       
         if(l.ejecutar(btn02, 0, 2, m, jx, jo)==1){
             reiniciar();
         }
    }//GEN-LAST:event_btn02ActionPerformed

    private void btn12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn12ActionPerformed
        // TODO add your handling code here:
         turnar(); 
        l.raya(m, fila1, 1, 0, 2);
         if(l.ejecutar(btn12, 1, 2, m, jx, jo)==1){
             reiniciar();
         }
    }//GEN-LAST:event_btn12ActionPerformed

    private void btn20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn20ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel1;
    private javax.swing.JButton btn00;
    private javax.swing.JButton btn01;
    private javax.swing.JButton btn02;
    private javax.swing.JButton btn10;
    private javax.swing.JButton btn11;
    private javax.swing.JButton btn12;
    private javax.swing.JButton btn20;
    private javax.swing.JButton btn21;
    private javax.swing.JButton btn22;
    private javax.swing.JPanel centrovertical;
    private javax.swing.JPanel derechavertical;
    private javax.swing.JLabel diagonal1;
    private javax.swing.JLabel diagonal2;
    private javax.swing.JPanel fila1;
    private javax.swing.JPanel fila2;
    private javax.swing.JPanel fila3;
    private javax.swing.JPanel izquierdavertical;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel jo;
    private javax.swing.JLabel jx;
    private javax.swing.JPanel panel1;
    private javax.swing.JPanel panel2;
    // End of variables declaration//GEN-END:variables
}
